### ISSUE TITLE
Compile Releases Transform - error logging

### ISSUE THREAD

**Issue by pindec** [open-contracting/kingfisher-process#129]
We have a publisher with some discrepancies between the number of distinct OCIDs in releases and records. 

The compile-transform mostly agrees with the number of distinct OCIDs in records, but sometimes with the number of distinct OCIDs in releases (see [this query in a colab notebook](https://colab.research.google.com/drive/1l3qF9U4lYTVUudy36loRJqL5UNkq2pmk#scrollTo=X1DUWCU2QPTC) for details). 

Error logging on compile-releases would be helpful to track down any issues.

**Comment by jpmckinney** [comment]
I'm reading the table in the colab notebook, and the number of distinct OCIDs in records and compiled releases is always equal until the last month, which suggests that perhaps the records source is a bit behind the releases source.

Anyhow, the discrepancy is not due to errors, so there is nothing to log. There are other issues for better error handing of the compile-releases transform like #204 and #222.
