### ISSUE TITLE
Running delete-collections takes more than a week on the live server

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-process#150]
What can we do about this?

**Comment by jpmckinney** [comment]
Looking at the delete_collection method: https://github.com/open-contracting/kingfisher-process/blob/23be995fd2dce308642fa98ddd72727e72357eaf/ocdskingfisherprocess/database.py#L554

1. All the queries use views (`release_with_collection`, `record_with_collection`, `compiled_release_with_collection`) and I'm not sure that PostgreSQL is using any index for `collection_id`, or that it's possible to add an index on a view. Can we try instead not using the views (in any queries)? The views should only be to ease writing queries for analysts, in scenarios where performance is not critical.
1. Shouldn't the checks (and check errors) relate to the `data` table, independent of the collection of which they are a part, since the collection makes no difference to the output of the check? That would eliminate the need to delete as many rows, but would require some re-architecture.
1. Similarly, upgrading releases and records doesn't depend on the collection, and can be tied directly to the `data` table.
1. It might be that using ON DELETE CASCADE (with indices) will be much faster (and less error-prone) than writing out every DELETE query and worrying about subquery performance, etc.

In general, running EXPLAIN on queries shows whether there is an obvious optimization missing (e.g. doing table scanning instead of using an index)

Separately:

1. A bug: We delete from `release_check_error`, but not `record_check_error`
1. Can we update database-tables.png to include `record_with_collection`?

**Comment by odscjames** [comment]
We recently added logging, and this confirmed a suspicion that points to a simple change to speed up this process.

The delete queries can be split into 2 types; the ones that delete for a specific collection and the ones that delete other data that is no longer in use. To be exact, they can be split into "Most of the tables" and "data and package_data table". 

The query to delete from "data" is the very slow one; while the first type of deletes ran in seconds for a collection, the "data" delete is taking more than a day.

The way the delete process currently works, these slow queries are called multiple times per use of the "delete-collections" command. We should change this so it only runs them once per use of the "delete-collections" command.


ps. Let me check some points with others before commenting on the above comment

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Speed up kingfisher delete by only deleting from "data" and "package_data" once per use of the "delete-collections" command](https://trello.com/c/vY2LAlin/68-speed-up-kingfisher-delete-by-only-deleting-from-data-and-packagedata-once-per-use-of-the-delete-collections-command)

**Comment by odscjames** [comment]
> Almost all the queries use views (release_with_collection, record_with_collection, compiled_release_with_collection) and I'm not sure that PostgreSQL is using any index for collection_id, or that it's possible to add an index on a view. Can we try instead not using the views (in any queries)? The views should only be to ease writing queries for analysts, in scenarios where performance is not critical. The views should never be used in Kingfisher code.

Let me double check that, because my understanding was that views will still use indexes where possible. (There is also materalised views, but due to the space requirements of those we probably don't want to use them).

> Shouldn't the checks (and check errors) relate to the data table, independent of the collection of which they are a part, since the collection makes no difference to the output of the check? That would eliminate the need to delete as many rows, but would require some re-architecture.

No -  the checks relate to a bit of data and the package info from the package_data table put together. We should think about this tho; in theory if you scrape the same API at 2 different times and the data and package_data is totally unchanged we should be able to use the same check result - tho #122 will complicate that!

> Similarly, upgrading releases and records doesn't depend on the collection, and can be tied directly to the data table.

Again that transform does include the package table. Altho, because there is no complication from extensions, it might be possible to do something here.

> It might be that using ON DELETE CASCADE (with indices) will be much faster (and less error-prone) than writing out every DELETE query and worrying about subquery performance, etc. #96

Possibly. I'll think about how we could test that. That wouldn't help with the data or package_data table tho, and data is a really big table we need to tackle.

> A bug: We delete from release_check_error, but not record_check_error

Fixed in pull request above

> Can we update database-tables.png to include the views?

https://github.com/open-contracting/kingfisher-process/issues/182

**Comment by odscjames** [comment]
We have been looking into this. Most queries are fine, with a few being really slow.

collection_file_item is one - we have dug into this with EXPLAIN but nothing obvious came out. It's currently 11GB in the database.

There is also the data table. We need to experiment with some approaches to tackle this one - it's one of the biggest in the database and currently is at 380 GB!

I don't know if deleting from package_data is slow or not - but that table is currently only at 10 GB so is less important than data.

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make sure delete is working well in Kingfisher Process](https://trello.com/c/iN5iQ7Ye/79-make-sure-delete-is-working-well-in-kingfisher-process)

**Comment by odscjames** [comment]
I have been looking into the data table, as that is the biggest. @kindly made a comment that IN can be slow, and we should look at joins instead.

If you run:

> CREATE INDEX tmp_release_data_id ON public.release (data_id);
> CREATE INDEX tmp_record_data_id ON public.record (data_id);
> CREATE INDEX tmp_compiled_release_data_id ON public.compiled_release (data_id);
> 
> SELECT data.id FROM data
> LEFT JOIN release ON release.data_id = data.id
> LEFT JOIN record ON record.data_id = data.id
> LEFT JOIN compiled_release ON compiled_release.data_id = data.id
> WHERE release.data_id IS NULL AND record.data_id IS NULL AND compiled_release.data_id IS NULL
> LIMIT 100;

You will get a result in 4 mins. 

(I am now dropping tmp indexes.)

I will talk to @kindly about this, and how we can use this to get the deletes on data table moving.

**Comment by odscjames** [comment]
Have talked to @kindly - we were wondering if the current delete SQL might do better once those indexes are added, but we aren't sure and also we have now build up a lot of data rows to delete which makes for one giant transaction!

Instead, we are going to try some Python that uses the select sql above to get ID's in blocks of 1,000 or 10,000 and then deletes them, keeps going until none left. This also has the advantage that if it runs for a day and then it's aborted by something (server reboot, impatient operator) some work will still have been done and committed to the DB.

**Comment by odscjames** [comment]
This finished overnight - it only deleted 600K rows, or 0.85% of them. I guess the de-dupeing of data when a collection is run multiple times really paid off!

Now setting this up to be released properly.

**Comment by odscjames** [comment]
Have been monitoring delete over last month. collection_file_item is still slow, it gets stuck deleting collection 502. However 

    SELECT id FROM collection_file WHERE collection_id = 502; 

runs in seconds and returns 4,433,900 rows - so I guess it's the delete which is taking time here. We will try deleting in blocks, like we did with data table.

**Comment by odscjames** [comment]
Whoops, that was the wrong SQL to test: it should be

    SELECT collection_file_item.id FROM collection_file_item 
            JOIN collection_file ON collection_file_item.collection_file_id = collection_file.id 
            WHERE collection_file.collection_id = 502

It still runs in seconds and return 4M rows, will try block approach

**Comment by odscjames** [comment]
This has been running all weekend on live server, and it is doing the work but very slowly. At least thanks to the block approach the work is actually being commited and is not lost! I will look at this again soon.

**Comment by odscjames** [comment]
We have identified an index to add that speeds up this - doing proper pull request now

**Comment by odscjames** [comment]
Entire delete process ran in less than an hour this morning (at 2am, on it's regular weekly cron slot). I think the main headline thing in this issue can now be closed, but we should do a quick sweep to see if there any other suggestions we want to put in another issue to discuss later.

**Comment by jpmckinney** [comment]
From my first comment:

1. The queries using `*_with_collection` views don't seem to have performance issues, so we can ignore this suggestion. I'm not sure that app code should use views (and should instead join tables directly, to avoid an extra layer of indirection), but we can wait until we change the views (which might never happen) to consider that change.
1. Good point about extension schema and package metadata potentially changing. I don't think there is a low-complexity way to reduce the number of rows in the checks table.
  * In terms of optimizing the check transform (i.e. to skip re-doing checks if not required), I created https://github.com/open-contracting/lib-cove-ocds/issues/36.
1. Good point about the package metadata potentially changing. I don't think there is a low-complexity way to reduce the number of rows.
  * In terms of optimizing the upgrade transform: The upgrade method is fast; although the release / record data is upgraded the same way regardless of package metadata, the extra complexity to get time-savings is not worth it – i.e. determining whether we already calculated the upgraded data in an earlier collection (in which case we can just get the id for its data row), in order to save a little time by only upgrading the package metadata.
1. Already in #96

Unless I missed something, I think we can close this issue and move the related card to Done.
