### ISSUE TITLE
Serve API and web app from process.kingfisher.open-contracting.org

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-process#158]
Not http://process.ocdskingfisher.opendataservices.coop/

Once complete, update the UptimeRobot monitor: https://uptimerobot.com/dashboard#783273034

**Comment by odscjames** [comment]
So I thought this would be a easy change, just add ServerAlias to the apache conf.

It doesn't work with a hyphen in. If you take the hyphen out and add an entry to your /etc/hosts it works totally fine.

I'm not the only one with this problem, but no idea why ....

*  https://stackoverflow.com/questions/20387123/apache-hyphen-in-servername-breaks-virtualhost
*  https://stackoverflow.com/questions/48085852/hyphen-in-fqdn-not-working-with-apache-2-4-18-on-ubuntu

**Comment by jpmckinney** [comment]
Which files are involved in the change?

One of those answers mentions that the issue (in their case) was that they had declared the virtual host twice.

**Comment by odscjames** [comment]
All I did was add a new ServerAlias line to https://github.com/OpenDataServices/opendataservices-deploy/blob/master/salt/apache/ocdskingfisherprocess.conf I did check for virtual hosts. I thought it would be easy, which is why I quickly tried to do it before an interview and then had to stop!

I will try to dig into this; if this version of Ubuntu has problems with hyphens in names that might have ramifications for other server work you want us to do, so I think it's important.

**Comment by odscjames** [comment]
This works perfectly on the dev server; which is frustrating. They are both on the same version of Ubuntu and have the same version of the Apache2 package installed. These servers are on different hosts; it's possible that a host has done something different to one of the base images; tho if that turns out to be it I will be very surprised.

However as we plan to host doc servers on Bytemark (same place as test server) I'm now more hopeful this shouldn't hold other work up, tho it would still be good to work out what is going on.

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Serve API and web app from process.kingfisher.open-contracting.org](https://trello.com/c/aIgP4fhz/40-serve-api-and-web-app-from-processkingfisheropen-contractingorg)

**Comment by odscjames** [comment]
This is still an issue

# Test failure

Deploy as normal.

Go to http://process.kingfisher.open-contracting.org/  - see standard Apache page

Just to be totally sure, on the server run this and see your requests:

    tail /var/log/apache2/access.log -f

# Test success with no hpyhen

Edit /etc/apache2/sites-available/ocdskingfisherprocess.conf , remove the hyphen

            ServerName process.kingfisher.opencontracting.org

Reload Apache

    /etc/init.d/apache2 reload

Edit your computers hosts file and add

     95.216.243.15         process.kingfisher.opencontracting.org

Go to http://process.kingfisher.opencontracting.org/app - see webpage - it works.

Just to be totally sure, on the server run this and see your requests:

    tail /var/log/apache2/other_vhosts_access.log -f

# Conclusion 

It really is something about the Hyphen, but I have no idea what.

**Comment by jpmckinney** [comment]
Was this after deploying c0cddef9c090eb15e236118fe955a78170098eb5 ?

**Comment by jpmckinney** [comment]
While removing the hyphen changes behavior, it's not clear to me that there isn't another cause further up the chain that's the problem ([third-cause fallacy](https://en.wikipedia.org/wiki/Correlation_does_not_imply_causation#Third_factor_C_(the_common-causal_variable)_causes_both_A_and_B)).

There's another issue here where sadly the two commenters don't expand on what the issue could be: https://serverfault.com/questions/928834/virtualhost-with-two-dashes

**Comment by odscjames** [comment]
> Was this after deploying open-contracting/deploy@c0cddef ?

Yes

> it's not clear to me that there isn't another cause further up the chain that's the problem

True but I currently have no idea what that could be or ideas for tests I could run to narrow that down. 

Apart from just thought; we should test again soon and look for IP4 vs IP6 differences?

**Comment by odscjames** [comment]
Odd: http://scrape.kingfisher.open-contracting.org/ works

**Comment by jpmckinney** [comment]
http://process.kingfisher.open-contracting.org/app/collection magically works with the new server. Can we update all reference to kingfisher.opendataservices.coop to kingfisher.open-contracting.org?

**Comment by jpmckinney** [comment]
That was easy enough, actually. I also updated UptimeRobot and redeployed KF Process.
