### ISSUE TITLE
Switch to password-less Basic Authentication instead of non-standard ApiKey

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-process#159]
For example, it is what Stripe does: https://stripe.com/docs/api/authentication

Downsides of non-standard authentication type include:

* not being able to access the API via a browser
* longer commands like `curl -H 'Authorization: ApiKey …` instead of `curl -u …:`
* Swagger not being able to produce an interactive form

**Comment by odscjames** [comment]
Just so we are clear, can I ask what the user case for accessing it like this is? If it's users performing actions and the CLI wasn't suitable, for instance, I'd maybe think about adding some kind of authentication to /app/ and then letting actions be done straight from the web page.

(Authorization header is relatively standard across OAuth-based API's which is why we picked it BTW but happy to switch if another option turns out to be more practical.)

**Comment by jpmckinney** [comment]
Basic Authentication still uses the Authorization header, but with a standard [Authorization type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication#Authentication_schemes) (`Basic`) instead of a non-standard type (`ApiKey`).

A more complete implementation of Basic Authentication would respond with a [WWW-Authenticate](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/WWW-Authenticate) response header, like in this [Flask snippet](http://flask.pocoo.org/snippets/8/).

The use case is other systems that need to integrate with the Kingfisher system (like the data quality tools work). In general, following standards makes such integration simpler and less error-prone (e.g. being able to use existing Basic Authentication components instead of writing that code oneself).

**Comment by jpmckinney** [comment]
After switching to queues, Scrapy would just enqueue its items instead of sending them via an HTTP request, so optimistically closing.
