### ISSUE TITLE
Add release, record and compiled release counts to collections table

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-process#183]
A frequent need is to check how many releases, records or compiled releases a collection contains. This helps an analyst to identify the correct collection to work with and also to check whether collections contain the expected number of releases, records or compiled releases.

Currently I run the query below to add these counts to the collections table for a specific publisher, but this takes a few minutes to run and needs running each time you open a data feedback report template notebook.

Would it be much work to add generating these counts to the kingfisher-process pipeline, so that each time a new collection is loaded, the number of releases, records and compiled releases is added to the entry in the collections table?

Query:

```SQL
  with collection_ids AS (
  
    SELECT
        id
    FROM
        collection
    WHERE
        source_id LIKE %s ESCAPE ''
  
  ), release_counts AS (
    
    SELECT
      collection_id,
      count(*) as release_count
    FROM
      release_with_collection
    WHERE
      collection_id IN (SELECT * FROM collection_ids)
    GROUP BY
      collection_id
  
  ), record_counts AS (
  
    SELECT
      collection_id,
      count(*) as record_count
    FROM
      record_with_collection
    WHERE
      collection_id IN (SELECT * FROM collection_ids)
    GROUP BY
      collection_id 
  
  ), compiled_release_counts AS (
  
    SELECT
      collection_id,
      count(*) as compiled_release_count
    FROM
      compiled_release_with_collection
    WHERE
      collection_id IN (SELECT * FROM collection_ids)
    GROUP BY
      collection_id 
  
  )
  
  SELECT
    id,
    source_id,
    data_version,
    store_start_at,
    store_end_at,
    sample,
    check_data,
    check_older_data_with_schema_version_1_1,
    transform_type,
    transform_from_collection_id,
    deleted_at,
    release_count,
    record_count,
    compiled_release_count
  FROM
    collection
  LEFT JOIN
    release_counts on collection.id = release_counts.collection_id
  LEFT JOIN
    record_counts on collection.id = record_counts.collection_id
  LEFT JOIN
    compiled_release_counts on collection.id = compiled_release_counts.collection_id
  WHERE
    source_id LIKE %s ESCAPE ''
  ORDER BY
    id ASC
```

**Comment by jpmckinney** [comment]
Is this more appropriate in Views? Right now, Process contains no aggregate statistics, so there's presently a clear distinction between the two projects.

**Comment by duncandewhurst** [comment]
It could be in views, but the information is useful when an analyst is choosing which collection to work with, so it would be most convenient to have it in the collections table.

Also, this information is useful to have immediately after running a scrape, to help with any debugging or sense checking, whereas views run overnight.

@pindec @mrshll1001 @yolile may have an opinion.

**Comment by odscjames** [comment]
>  In what conditions can the values be out of date?

Under what I've outlined above, they shouldn't do, but if they were expanded in the future they could. For example if it was said "can they update during storage for a progress indication?" they could easily get out of date.

 > I think _count is a more common way to name such fields.

Fair enough - cached_releases_count, cached_records_count, cached_compiled_releases_count

**Comment by jpmckinney** [comment]
Why do we send signals, instead of just directly interacting with the queue? It seems like unnecessary indirection.

**Comment by odscjames** [comment]
It helps with current and future flexibility - it lets different behavior be configured at different times and is easily changed.  For example, we already change the systems behavior via signals based on whether an config option is set. Something I can see happening is changing it based on whether it's run from CLI or Web - some tasks you might want to do straight away if run from CLI, but might want to push through Redis if done via Web to make sure the HTTP response in still fast. 

It also keeps that wiring together in one place, which makes it a bit easier to see what is going on. It also gives us more options for unit testing.

If that's ok, can we consider this one fully specced and ready to go? I will comment on Trello card.

**Comment by jpmckinney** [comment]
I'm still confused as to why we have multiple implementations of publish-subscribe / delayed jobs / queues, as discussed in https://github.com/open-contracting/kingfisher-process/pull/152#issuecomment-491908018

Right now, as far as the signals/blinker code goes, we have one emitter and one subscriber… Wouldn't it be much simpler to just do a plain Python method call? If we had multiple emitters or multiple subscribers, then it would make sense to use some form of publish-subscribe implementation – though even then I'd prefer to have one implementation (Redis) rather than two, unless there is a very clear advantage to having two.

**Comment by odscjames** [comment]
> I'm still confused as to why we have multiple implementations of publish-subscribe / delayed jobs / queues

If you mean signals/blinker and Redis, they do different things. Redis works across processes. It's sometimes overkill to push every task through a Redis pipe - some can just run instantly with no problems - and also to do so involves extra complexity as you have to think about what happens if there is a delay.

> Right now, as far as the signals/blinker code goes, we have one emitter and one subscriber for each event… 

That's true at the moment, but this is trying to keep that flexible for the future. 

Can I suggest that this would be more suitable for a wider discussion? You linked to #152 which has some much bigger conversations to have, and it would be good to take time to expand on those. But the path suggested here fits into the existing paradigms we use in this software, and this issue started with a simple request. It would be good to get that request done, and I don't know if we need to have those wider discussions before we do that?

**Comment by jpmckinney** [comment]
It's not clear to me that Redis is more complex (from the perspective of the Python code, there's about one line of code for emitting and subscribing whether it's blinker or Redis).

If we are using a dedicated 'queue' for the new event type (which we should), then there will hardly be a delay (at least none worth being concerned about).

In terms of flexibility for the future, I think it is vastly more likely that we will have subscribers that are not in the same process. For example, the new Data Quality Tool can subscribe to the 'collection is done' event. For that to work, the event needs to be visible outside the process, i.e. we should use our current Redis pattern, not our blinker pattern.

So, in terms of choice of existing paradigm, we should use Redis here. It's not clear to me that we'd ever want to broadcast the 'collection is done' event to multiple parts of the same process, in a way that couldn't be done with simple method calls. For that to be the case, we'd need to have code running in the same process that we somehow didn't know in advance was interested in the event…

I think in `mark_collection_store_done` can put a [pub/sub](https://redis.io/commands#pubsub) message in a channel, so that other systems like the Data Quality Tool and Kingfisher Views can be notified – and not use blinker at all for this.

**Comment by jpmckinney** [comment]
In terms of wider discussions, in my experience, they tend to never occur, *unless* the opportunity is taken to have them at the time that a relevant issue arises. It might seem like we're delaying responding to the request, but it's better to look at it as making progress on both the wider discussion and the particular request at the same time.

**Comment by robredpath** [comment]
> In terms of wider discussions, in my experience, they tend to never occur, unless the opportunity is taken to have them at the time that a relevant issue arises. 

@jpmckinney @odscjames Agreed; this is often the case. Let's take this opportunity to make this case different. Shall we try and get an introductory call in early next week to work out what the issues to discuss are and work out how far we need to take them at this point? We don't need to solve everything right now, for sure, but at the same time it'd be good to give some thought to this broader architectural issue if it's getting in the way of forming consensus now - especially as this is a conversation that's come up in a couple of places.

> it's better to look at it as making progress on both the wider discussion and the particular request at the same time.

I'm wary of architecture-by-default, here - it's very easy to make a series of decisions, which then become the established norm, without reference to future plans.

**Comment by odscjames** [comment]
> So, in terms of choice of existing paradigm, we should use Redis here.

I think there has been some confusion here - I actually did suggest using Redis for this and doing the actual work in a separate process. https://github.com/open-contracting/kingfisher-process/issues/183#issuecomment-530890604

I recognise tho this has come up in other places before and it would be good to get it right, and so as @robredpath suggests a call may be good?

**Comment by jpmckinney** [comment]
Sounds good – I'm free at the usual time on Tuesday (or other times). My main confusion is on the use of signals/blinker instead of method calls (especially if it's just used to put a message in Redis).

**Comment by robredpath** [comment]
Thanks, both - I've sent you an invite

**Comment by odscjames** [comment]
The issue about removing Blinker I have put separately so it can be prioritised separately; do this one without using Blinker. If #189 is prioritised and done before this one then that's easy; if it prioritised the other way round make sure a Python call is put through a central place as described in #189

**Comment by odscjames** [comment]
This has now been deployed to master. A process is running to update all old collections. Will mak sure that is fine before calling done.

**Comment by odscjames** [comment]
Old collections have been updated. If @duncandewhurst @pindec could confirm they are happy?

**Comment by duncandewhurst** [comment]
Looks great, thanks James!
