### ISSUE TITLE
update_requirements, and thus frozen requirements system is broken

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-process#195]
When the script is run now, the following line appears in requirements_dev.txt and requirements.txt

    -e git+git@github.com:open-contracting/kingfisher-process.git@cd1d383bce6f21c156d52c1044c254719cf57d5a#egg=ocdskingfisher

This breaks on Travis, as the Travis process is not set up with a user that can SSH into GitHub.

This will also break on our live deploy, as again a SSH user for GitHub isn't set up there.

And we can probably expect this to break on other users setups too.

We think commit https://github.com/open-contracting/kingfisher-process/commit/6552d309c66f520f427877735f5a19db923f039a caused this. The change to  "-e ." may be causing this bad line to appear. 

(Note, this error only appeared when we tried to update requirements.txt, which explains why Travis worked till now.)

We need to test further and then suggest fixes.

**Comment by rhiaro** [comment]
update_requirements.sh also adds the following bad line to requirements.txt and twice to the top of requirements_dev.txt for the same reason:

`Skipping line in requirement file [requirements.in] because it's not clear what it would install: .
  (add #egg=PackageName to the URL to avoid this warning)`

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make sure Python dependencies are working, including knock on effects](https://trello.com/c/0mawoVXt/116-make-sure-python-dependencies-are-working-including-knock-on-effects)

**Comment by jpmckinney** [comment]
We can put setup.py's `install_requires` back into requirements.in (it was moved to simplify Views installation as mentioned in the commit message, but if Views no longer requires Process after https://github.com/open-contracting/kingfisher-views/issues/34, then that's not a problem).

I'm not 100% certain of the value of requirements_dev.* As described in https://github.com/open-contracting/lib-cove-ocds/pull/28#issuecomment-533618374, using whatever maximum versions are available for flake8, pytest, etc. seems fine.

**Comment by jpmckinney** [comment]
Taking another look at setup.py… I'm not sure why we have it at all, considering `deploy` doesn't interact with it, and considering we want to treat Process as an app, not as a library.

In that case, I think it'd make sense to eliminate setup.py and have requirements.in, requirements.txt and requirements-dev.in files (I'm not sure freezing development dependencies in requirements_dev.txt is worth the extra effort and complexity; if we drop `requirements_dev.txt`, developers will have to install both `requirements.txt` and `requirements-dev.in` separately, but this doesn't seem like a big deal). Preferably `update_requirements.sh` would just be a common script we can `curl http://url.for/script | bash -` instead of having it in lots of repos.
