### ISSUE TITLE
CoVE output reports OCDS fields as additional fields

### ISSUE THREAD

**Issue by romifz** [open-contracting/kingfisher-process#221]
I created a new collection in Kingfisher with CLI commands and loaded [data from Vialidad Argentina](https://datosabiertos.vialidad.gob.ar/api/ocds/release/all). For the moment they publish their data as a release_list, therefore there is no package data included.

Here I copied the list of additional fields reported by CoVE. Some are legit (because of extensions not declared) but there are some like `buyer/id`. Am I missing something? 

path | field | count
-- | -- | --
/releases | bids | 158
/releases | parties | 158
/releases | relatedProcesses | 158
/releases | workDetails | 158
/releases/awards | currentValue | 97
/releases/awards/contractPeriod | durationInDays | 97
/releases/awards/suppliers | id | 89
/releases/buyer | id | 158
/releases/contracts | amendments | 85
/releases/contracts | progress | 86
/releases/contracts | relatedProcesses | 7
/releases/contracts/implementation | certificates | 89
/releases/contracts/implementation/transactions | payee | 86
/releases/contracts/implementation/transactions | payer | 86
/releases/contracts/implementation/transactions | value | 86
/releases/contracts/items/unit | id | 88
/releases/contracts/period | durationInDays | 87
/releases/planning | milestones | 158
/releases/planning/budget | currentValue | 128
/releases/planning/budget | openingValue | 104
/releases/planning/milestones | value | 92
/releases/tender | additionalProcurementCategories | 158
/releases/tender | amendments | 158
/releases/tender | contractPeriod | 132
/releases/tender/awardPeriod | durationInDays | 73
/releases/tender/items | deliveryLocation | 94
/releases/tender/procuringEntity | id | 158
/releases/tender/tenderers | id | 127
/releases/tender/tenderPeriod | durationInDays | 133

**Comment by jpmckinney** [comment]
cc @duncandewhurst @pindec in case they've seen something similar.

**Comment by duncandewhurst** [comment]
Those are all fields that were added in OCDS 1.1.

Because the version of the data isn't known, Kingfisher is using CoVE to check the data against both the 1.0 and the 1.1 schemas (in `release_check` there are two rows for each release, one with `override_schema_version` set to 1.1 and one with `override_schema_version` not set).

I think that's the behaviour we want when the version of the data isn't known.

I've updated the [additional fields query](https://colab.research.google.com/drive/1Q1L4uZYYGFyj_pGkot5LipxMrgzeJvuy#scrollTo=1KTukxf6eBZJ&line=3&uniqifier=1) in the data feedback notebook to add `schema_version` column so you can filter to show only the additional fields relating to OCDS 1.1.

I also added the following note:

> *Data with no package, or where a version is not declared, is checked against both the 1.0 and 1.1 schemas, use the `schema_version` column to distinguish which schema the results relate to*

**Comment by romifz** [comment]
Thank you Duncan! It makes sense.

I'm closing this since it seems there is no issue with Kingfisher.
