### ISSUE TITLE
compile-releases: Store warnings (in collection_note table)

### ISSUE THREAD

**Issue by pindec** [open-contracting/kingfisher-process#222]
As an analyst I need to know whether the compilation script encounters data quality issues in the source data in order to judge whether the compiled collection may be missing data.

Example - uk_contracts_finder collection 606 has all award/suppliers with same id (and no parties array). Compiling into collection 608 means all but one supplier is removed. 

It would be helpful for compile warnings to be stored in the compiled release collection. 

This should include warning about any array with non-unique local ids.

**Comment by pindec** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Process: errors in compilation need to be flagged](https://trello.com/c/SHoVbDwE/145-process-errors-in-compilation-need-to-be-flagged)

**Comment by jpmckinney** [comment]
Compilation doesn't presently check for this, but new warnings can be implemented. These would still have to be captured and reported by Kingfisher.

Can you share a specific release that has this issue, to be sure that I understand the problem?

**Comment by pindec** [comment]
Sure.

In collection 606, release with OCID ocid = 'ocds-b5fd17-2f6874ab-adc8-11e6-9901-0019b9f3037b' has 37 suppliers with distinct names, all with id = 0. There is no parties array, so this is deprecated/1.0 use of suppliers anyway (suppliers have contactPoint and address fields). Identifier fields are empty or null. There is just one release with that OCID.

Truncated data:

`"suppliers": [
                {
                    "id": 0,
                    "sme": false,
                    "name": "Aquilant Limited",
                },
                {
                    "id": 0,
                    "sme": false,
                    "name": "Aspen Medical Europe Limited",
                },
   {
            "id": 0,
            "sme": false,
            "name": "B. Braun Medical Limited",
        },
... etc
`

Same OCID in compiled_release collection 608 has one supplier (truncated):

`"suppliers": [
                {
                    "id": 0,
                    "sme": false,
                    "name": "Ypsomed Limited",
                }
            ]`

This supplier is the final object in the award.suppliers array from collection 606.

Same can be seen from running
`select * from views.award_suppliers_summary 
where ocid = 'ocds-b5fd17-2f6874ab-adc8-11e6-9901-0019b9f3037b'`
for each collection_id.

**Comment by jpmckinney** [comment]
I've released a new version of ocdsmerge that, by default, with issue a Python warning if there are duplicate IDs in a single release. Kingfisher will have to catch those warnings and do something with them.

Alternately, Kingfisher can instruct ocdsmerge to fail entirely:

```python
from ocdsmerge import merge, RAISE

releases = [
  # OCDS JSON objects…
]
merge(releases, collision_behavior=RAISE)
```

**Comment by jpmckinney** [comment]
Note: I updated my comment above.

I release a new version of ocdsmerge that now offers some alternatives to the default merge routine. See the documentation: https://github.com/open-contracting/ocds-merge#working-with-degenerate-data

**Comment by jpmckinney** [comment]
@pindec Please share the script you used to edit the Contracts Finder data in https://crm.open-contracting.org/issues/5344#note-8

**Comment by jpmckinney** [comment]
Important caveat that I'll add to the OCDS Merge documentation: presently, the alternatives to the default merge routine (e.g. keeping all objects regardless of `id`) affect all JSON paths, not just the problematic ones.

**Comment by jpmckinney** [comment]
I've changed the feature so that non-default rules are applied to specified fields only.

**Comment by jpmckinney** [comment]
Contracts Finder seems to have fixed their issue. `dominican_republic_api` has duplicates, but as far as we know, they are actual duplicates (and therefore only one should survive).

For now, I added a commit, so that these warnings are stored in `collection_note`. If we find a need, we can add a way for a spider in Kingfisher Collect to be configured with [merge rules](https://ocds-merge.readthedocs.io/en/latest/handle-bad-data.html), and those can be sent the Kingfisher Process in the `spider_opened` signal, and then saved to its `Collection.options` column.

The merge rules are expressed as `{('tender', 'tenderers'): ocdsmerge.APPEND}`. In Kingfisher Collect, we would probably do: `merge_rules = {"tender/tenderers": "APPEND"}`, to be JSON-serializable, and Kingfisher Process would similarly store this JSON in the database. Then, in `compiler.py`, we might first do something like `rules = tuple(collection.options.get("merge_rules", {}))` (since arguments to `_get_merger` need to be hashable), and then in `_get_merger`, we'd do:

```python
    rule_overrides = {tuple(path.split("/")): getattr(ocdsmerge, v) for path, v in tuple(rule_overrides.items())}
    return ocdsmerge.Merger(patched_schema, rule_overrides=rule_overrides)
````
