### ISSUE TITLE
No setup.py

### ISSUE THREAD

**Issue by tarnh** [open-contracting/kingfisher-process#228]
Dear developers,

I'm using ArchLinux and therefore packaging any pip package for my distro.

But for kingfisher-process I don't know what to do since it lacks a `setup.py` file.

**Comment by jpmckinney** [comment]
Hi @tarnh, kingfisher-process is intended to be used as an application, rather than as a reusable Python package, so there is no setup.py. Have you already seen the installation documentation accessible from https://kingfisher-process.readthedocs.io/en/latest/ ?

kingfisher-process is still a little rough around the edges in terms of re-use, but we are happy to help if you encounter any challenges. Can you tell us a little more about your use case / what you want to use kingfisher-process for?
