### ISSUE TITLE
config is passed around a lot but is rarely used

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-process#230]
For example, I can't see what the Store class does with the config.

In general, we shouldn't be passing full configurations all over the app, and should instead provide the minimum needed; for example, the DataBase class just needs the `database_uri`. Otherwise, it is very easy to introduce strange 'action-at-a-distance' behavior through the configuration.

**Comment by jpmckinney** [comment]
Is there a reason the config isn't parsed only once, like in Django and Flask apps? Django apps just parse settings once, whether for CLI (manage.py) or web requests.

**Comment by odscjames** [comment]
Passing around the config and database was a deliberate choice to make testing easier and cleaner. This means that you can inject different options as needed. We don't do this for the database currently, but we do do this for configs: https://github.com/open-contracting/kingfisher-process/blob/master/tests/test_standard_pipeline.py#L9

I did raise with other Dev's here for discussion that I was doing this, and I wasn't sure it was the "Pythonic" way to do things. But no objections were raised to this methodology.

> Otherwise, it is very easy to introduce strange 'action-at-a-distance' behavior through the configuration.

I'm not sure about "Otherwise" here; problems like this seem possible to introduce whenever there are config options, no matter how they are passed.

>  I can't see what the Store class does with the config.

At the moment, nothing, this was just done based on the above principals.

> Is there a reason the config isn't parsed only once, 

I think it is?

* Web access parsing - https://github.com/open-contracting/kingfisher-process/blob/master/ocdskingfisherprocess/web/app.py#L21 
* CLI access parsing - https://github.com/open-contracting/kingfisher-process/blob/master/ocdskingfisher-process-cli#L18  
* Migrations access - https://github.com/open-contracting/kingfisher-process/blob/master/ocdskingfisherprocess/maindatabase/migrations/env.py#L11 

Searching for load_user_config in the code base seems to confirm this?

**Comment by jpmckinney** [comment]
Okay, I think the simpler way is to just have the module load the config once (guaranteed) instead of (1) opening the possibility of multiple (possibly inconsistent) parsings and (2) having to pass a config variable around.
