### ISSUE TITLE
Automatically "expire" checks

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-process#234]
~~Chatting with @mrshll1001~~

~~We do ask people to delete collections when done, but it's easy to forget.~~

~~This would help clear out old collections and keep things running quickly.~~

**Comment by jpmckinney** [comment]
Should we create a CRM issue asking people which collections can be deleted? I think many are just unsuccessful scrapes.

For OCP, we'd want to keep any ‘full’ collections (ie not any bad scrapes) to be able to track improvements over time. Once the Data Quality Tool has processed these, we can archive and delete all but the most recent, which is useful to keep around for ad-hoc querying.

This suggests that new collections shouldn’t have an expiry, until (1) we know whether the scrape succeeded or failed (ideally we can have a web view to help identify and delete bad scrapes) or (2) the same source has a newer (full) collection.

**Comment by jpmckinney** [comment]
What operations in particular are affected by the database size? I noticed that not all foreign keys have indexes (SQLAlchemy doesn’t add them but default).

**Comment by jpmckinney** [comment]
Instead of expiring source collections, I think we can expire a collection's `record_check` and `release_check` rows (and set `check_data` to false to prevent their re-creation).

We can also expire a collection's transformations. However, let's hold off on deleting any of these until the DQT has had a change to process any remaining compiled collections.

In both cases, the deleted data can be deterministically re-created based on the source collection.

**Comment by jpmckinney** [comment]
In CRM 5953 we agreed on a policy to expire release_check and record_check rows, whose related collection ended more than 30 days ago. At the same time, we need to set `check_data` to `FALSE`, otherwise the cron job will re-create the checks.

If we needed to re-run checks, wed'd have to set `check_data` to `TRUE`:

```sql
UPDATE collection SET check_data = TRUE WHERE collection_id = ?
```

Then wait for the cron job to do the checks.

**Comment by jpmckinney** [comment]
Query is:

```sql
DELETE FROM record_check
WHERE id IN (
    SELECT rc.id
    FROM record_check rc
    JOIN record r ON rc.record_id = r.id
    JOIN collection c ON r.collection_id = c.id
    WHERE store_end_at < CURRENT_DATE - INTERVAL '1 month’
);
```

**Comment by jpmckinney** [comment]
I ran these manually on May 13, 2020.

**Comment by jpmckinney** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Kingfisher - identify and remove collections and views that are no longer needed](https://trello.com/c/Kdh785HF/223-kingfisher-identify-and-remove-collections-and-views-that-are-no-longer-needed)

**Comment by jpmckinney** [comment]
To check how much will change from expiring transforms of 30-day old collections:

```sql
SELECT id, source_id, data_version, transform_type
FROM collection
WHERE transform_type <> '' AND store_end_at < CURRENT_DATE - INTERVAL '1 month'
ORDER BY data_version;
```

We can then use the delete-collection command.

**Comment by jpmckinney** [comment]
I've run delete-collection on transforms that are more than 1 year old, to see how that affects disk space.

**Comment by jpmckinney** [comment]
We haven't had disk space issues in a while, so I don't think we need special logic for expiring checks.
