### ISSUE TITLE
Upgrade 1.0 to 1.1 Transform - Handling of data that is already 1.1

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-process#26]
Check data actually is 1.0 before trying to transform!

If it isn't, do we want to copy the data anyway? (I'm thinking about what the case would be if a collection had both 1.0 and 1.1 data, tho that sounds unlikely)

Can we mark this in status table, maybe a new column "data_was_not_1_0" boolean default false? We can then provide a clearer status report to the user. "There was no 1.0 data to transform" as a message immediately informs the user and means they don't waste time trying to run analysis against data that is actually exactly the same.

**Comment by jpmckinney** [comment]
Copying your earlier comments as FYI to other readers:

> I would still like to do this at the Kingfisher level
> A) We can avoid rewriting the same data back to the database, which will both be faster and save some space (or maybe we still want that data in the new collection? I'm thinking about what the case would be if a collection had both 1.0 and 1.1 data, tho that sounds unlikely. Whatever, I'd like to consciously discuss and make sure we do the right thing. )
> B) We can log that it wasn't 1.0, and then provide a clearer status report to the user. "There was no 1.0 data to transform" as a message immediately informs the user and means they don't waste time trying to run analysis against data that is actually exactly the same.

For context, it's common, in general (i.e. outside the context of the helpdesk), for data analysts to pre-process data along a standard pipeline, and then query the final dataset. So, all the data they intend to query should be in that final dataset. If the pre-processing causes no change to the data, they don't care. Also, in general, data analysts only query that final dataset – not the original or intermediate datasets; if they think there was an error in the pre-processing (rare), then they might look at those.

I think the helpdesk works the same way.

If we're concerned about space, I think we can consider options like scheduling collections for deletion after a reasonable period, giving analysts the option to automatically delete source collections after transformation, etc.

If a collection has both 1.0 and 1.1, the 1.0 should be upgraded and the 1.1 should be passed through (this is what OCDS Kit does). An upgrade shouldn't cause data loss.

I don't think we need to track the original version in a database column. I don't think a message to users is needed, because what matters is that the output is 1.1 so that the analysts queries will work as expected; the fact that the data was already 1.1 doesn't matter to the analyst for querying purposes.

**Comment by jpmckinney** [comment]
That's reasonable to me – though we can't know for certain that there isn't 1.0 data in a dataset without downloading it first.

Just throwing it out there: when LHS tells RHS which collection to use, can it say "any 1.0 data should be upgraded before being stored"? In that case, RHS wouldn't store the original 1.0 data.

Another option: I'd have to double-check how the database is currently set up, but we could have a linking table between collections and data. This would allow the same data to be in multiple collections – so if a transform produces no change, we can just link to the original data.

**Comment by odscjames** [comment]
> Another option: I'd have to double-check how the database is currently set up, but we could have a linking table between collections and data. This would allow the same data to be in multiple collections 

We already have the data and package_data tables that kinda do this!

**Comment by jpmckinney** [comment]
> We already have the data and package_data tables that kinda do this!

Great – so we might be able to leverage that :)

**Comment by jpmckinney** [comment]
In https://github.com/open-contracting/kingfisher-process/issues/270#issuecomment-662068451, the proposal is for Kingfisher Collect to indicate whether an upgrade is needed, and if so, Kingfisher Process would add it as a step.

Similarly, the Django branch has an addstep command, through which a CLI user can request an upgrade.

If nothing is indicated, Kingfisher Process does no upgrade.

Closing in favor of #270
