### ISSUE TITLE
Correctly handle NUL characters (control code)

### ISSUE THREAD

**Issue by yolile** [open-contracting/kingfisher-process#263]
Now if a ISO-8859-1 file is  processed by KP and the file contains the `\u0000` character it fails with a postgres error:

`DETAIL: \u0000 cannot be converted to text.`

KP should be able to remove that character in util.py.

@jpmckinney

**Comment by jpmckinney** [comment]
My reading of util.py is that it replaces `b'\\u0000`, which is the binary string `\u0000`, whereas we need to replace `b\u0000`, which is the binary NUL character.

**Comment by odscjames** [comment]
> My reading of util.py is that it replaces b'\\u0000',

From memory that was done to deal with data from the UK, and I'm sure I saw that working. If something has gone funny here we should double check that source too.

@yolile Do you have an example ISO-8859-1 file for testing this?

**Comment by jpmckinney** [comment]
The code was copied from https://github.com/open-contracting/kingfisher-vagrant/blob/a7b8f7d67081ae584ef15c421743043a514b7354/ocdskingfisher/util.py. `\x0a` (the newline character) was removed in #31. The list omits `\x01` (start of heading character), though probably by mistake.

I don't know why `b'\\u0000'` is included because `b'\\u0000' != b'\x00'`, and we do want to remove the NUL character.

**Comment by jpmckinney** [comment]
Based on [PostgreSQL's documentation](https://www.postgresql.org/docs/11/datatype-json.html), only the NUL character is a problem.

In the new version, we should just remove NUL characters, @jakubkrafka.

Since this problem came up in a collection this week, I'll add `\x00` to the old version as a hotfix.

**Comment by jpmckinney** [comment]
I figured out the mystery of `b'\\u0000'`. JSON strings can include `\u` escape sequences. If they do, they appear as `b'\\u0000'`. However, PostgreSQL's limitation is storing the actual NUL character, not an escape sequence of the NUL character.

**Comment by jpmckinney** [comment]
https://sentry.io/organizations/open-contracting-partnership/issues/2824257794/?project=5857059&query=is%3Aunresolved
