### ISSUE TITLE
Access to progress information for transforms and checks that run automatically

### ISSUE THREAD

**Issue by romifz** [open-contracting/kingfisher-process#265]
As an analyst, I would like to access progress information when transform collections and/or checks are running in the server, to estimate the remaining times and to confirm issues that may exist with the original collection or its transformed versions.

Although the analyst could make a guess of the time transformations/checks would take, there is the situation when there is queued work related to other collections. If the analyst is not familiar with the collections already in the queue, it can be hard to guess how much time it would take for the process to get to the transform or check needed.

**Comment by jpmckinney** [comment]
Related: https://github.com/open-contracting/kingfisher/issues/327

**Comment by duncandewhurst** [comment]
+1 to this, need to identify when transforms are just queued or if they have failed due to another issue

**Comment by robredpath** [comment]
This was raised again during the OCDS checkin recently. A workaround that we've used previous has been to copy the logs to somewhere that analysts have access to them, and then (extracted from the ODS internal troubleshooting process doc:)

 > Check the kingfisher process logs:
> Ask someone with root access (any ODS developer) to copy the log files from /var/log to a folder accessible by the ocdskfp user
> Check the collection id in the last occurence of the “Starting to transform collection” message (run `tac <log file name> | grep -m 1 "Starting to transform collection"`)
> If this is lower than the collection id you are investigating, then kingfisher is still working through older transforms (this can happen with very large collections, e.g. Colombia)

So, in the short term, we could look at solving this through filesystem perms and/or sudo access. Any preference @jpmckinney ? Personally I think that sudoers is probably easier as it's easier to keep track of and see than ACLs (if the fs even supports them - I've not actually checked) but I'm not too attached to that view.

**Comment by jpmckinney** [comment]
I prefer to keep the number of sudoers to a minimum.

I think the appropriate solution is to change [our configuration](https://github.com/open-contracting/deploy/blob/master/salt/ocdskingfisherprocess/logging.json#L21) to (1) use [RotatingFileHandler](https://docs.python.org/3/library/logging.handlers.html#logging.handlers.RotatingFileHandler) instead of SyslogHandler, and to (2) write the file to a location where analysts are likely to discover it. I suspect the file will be owned by ocdskfp, since ocdskfp owns the cron process writing the log file, but if not we can write a [factory](https://docs.python.org/3/library/logging.config.html#logging-config-dict-userdef) that [changes the owner](https://docs.python.org/3/howto/logging-cookbook.html#customizing-handlers-with-dictconfig).

**Comment by jpmckinney** [comment]
@odscjames fixed access in #277 by just adding a line to logrotate.conf to make the files world-readable – which is also a fine solution.

**Comment by jpmckinney** [comment]
The last few comments I think belong in #277. For the issue description, I'll close in favor of open-contracting/kingfisher#327

**Comment by jpmckinney** [comment]
I updated the troubleshooting doc to eliminate the step to copy the log file.
