### ISSUE TITLE
Have an overview of system, across Collect, Process

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-process#295]
(From discussion from https://github.com/open-contracting/kingfisher-process/pull/152#issuecomment-491908018 )

**Comment by duncandewhurst** [comment]
In particular, we need to be able to see whether checks are still running or complete.

**Comment by jpmckinney** [comment]
Which collection ID are you interested in? For now I can just share a SQL command for checking this.

**Comment by duncandewhurst** [comment]
It was 1368 (Moldova). I think they've completed now, but it would be good to see the SQL command to double-check (and add to add to the Kingfisher troubleshooting doc).

**Comment by jpmckinney** [comment]
Get the number of checked releases:

```sql
SELECT COUNT(*) FROM release_check WHERE release_id IN (SELECT id FROM release WHERE collection_id = 1368);
```

Get the number of releases:

```sql
SELECT COUNT(*) FROM release WHERE collection_id = 1368;
```

**Comment by duncandewhurst** [comment]
Ah yes, I'd looked at `release_check` but originally it was empty and I wasn't sure if that was because checks were still queued/running or because they had failed completely (as had happened with an earlier Moldova collection). I guess being able to check that depends on https://github.com/open-contracting/kingfisher-process/issues/301.

In the end I ran `check-collection` to be sure and once it had finished running `release_check` was populated.

**Comment by jpmckinney** [comment]
Adding some miscellaneous notes. I have a paper mockup from December that's more complete.

* Show the process status of the workers (i.e. to know whether they are running)
* Make it easy to identify empty or small collections, so that they can be easily deleted
* Scrapyd integration
  * Web form to start a crawl (and select configuration options, like whether to skip checks)
  * Option to display all source IDs in the UI, even if no collection exists for it

**Comment by jpmckinney** [comment]
In case I forget, I put a cleaned-up paper mockup and notes document here: https://drive.google.com/drive/folders/15TeYUmfg2LN_hIM0Szw6uaUsz7mGV74Y

**Comment by jpmckinney** [comment]
I'm removing Views from this issue, because it's run manually, and it generally takes less than 2 mins.

For the few cases where it takes longer, we should make it fast rather than build infrastructure to monitor its progress: https://github.com/open-contracting/kingfisher-views/issues/155

**Comment by jpmckinney** [comment]
When we rebuild the analyst's server, we can add the registry, whose Django backend makes it possible to see which jobs are running, and which steps have completed.

I think the main thing analysts want is #273 - it doesn't really help to know "oh, it's at 63% of the check step", etc. By reusing the registry's code, we have one less thing to maintain.

Okay to close this issue, @yolile ?

**Comment by yolile** [comment]
Yeap, that, plus the now documented queries for checking if the steps are complete, sounds good.
