### ISSUE TITLE
Document changes by Honduras

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-process#303]
For example, I see a new transform here: https://github.com/portaledcahn/edcahn_kingfisher/blob/master/kingfisher-processHN/ocdskingfisherprocess/transform/record_new_only.py

It would be good to catalogue their changes, so that we can consider similar features in Kingfisher Process.

**Comment by romifz** [comment]
In Honduras' version of kingfisher-process there is only one change: the addition of a "record" transform. I think the code in the repository is not updated, but the addition is heavily based in the compile transform, with the modifications needed to combine the releases + compiled release + versioned release into a record.

They needed this to be able to produce records from releases they fetch from two different publishers.

Then they have a module they call OCDS Hunter, which is in charge of loading data into kingfisher-process and run daily updates. My understanding of the code is that they use kingfisher-process' CLI commands to create collections and transformed collections since they have access to the source JSON data through shared folders.

I thought that OCDS Hunter updated Kingfisher's collections, but I can't see this in the source code (I think it's outdated). I'll check with one of the developers. But from recent conversations with them, I know they were getting issues because the whole process takes too much time due to the increasing volume of input data.

**Comment by jpmckinney** [comment]
Thanks! Yes, I think when we discussed it earlier, the suggestion was that their system should only update records that have new data – instead of updating all records, which will get slower over time.
