### ISSUE TITLE
Service error: compile-transformed collection is empty (no store_end_at value)

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-process#321]
**Which service is affected?**

Kingfisher Process
process.kingfisher.open-contracting.org

**What were you trying to do?**

Scrape OCDS records data using the following command:

```
curl -n http://collect.kingfisher.open-contracting.org/schedule.json -d project=kingfisher -d spider=portugal -d note="Started by Duncan."
```

**What error did you receive?**

There is no error message but the compile transformed collection is empty and there is no value in `store_end_at`:

id | source_id | data_version | store_start_at | store_end_at | sample | check_data | check_older_data_with_schema_version_1_1 | transform_type | transform_from_collection_id | deleted_at | cached_releases_count | cached_records_count | cached_compiled_releases_count
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1,532 | portugal | 2020-11-03 21:53:20 | 2020-11-03 21:56:24 | [NULL] | false | false | false | compile-releases | 1,531 | [NULL] | [NULL] | [NULL] | [NULL]
1,531 | portugal | 2020-11-03 21:53:20 | 2020-11-03 21:56:24 | 2020-11-04 14:45:47 | false | false | false | upgrade-1-0-to-1-1 | 1,530 | [NULL] | 0 | 1,153,041 | 0
1,530 | portugal | 2020-11-03 21:53:20 | 2020-11-03 21:56:24 | 2020-11-04 04:59:46 | false | true | true |  | [NULL] | [NULL] | 0 | 1,153,041 | 0

I had the same issue when local loading the same data from a bulk file in collections 1533, 1534 and 1535.

Based on checking an example, it looks like the source data includes linked releases in `releases` and a compiled release in `compiledRelease`. From [the docs](https://kingfisher-process.readthedocs.io/en/latest/transform/compile-release.html#compile-release-transform) I would expect the compile-transformed collection to be populated with the compiled releases from the records.

**Did you attempt a fix?**

I checked the logs and the `collection` table and it looks like transforms for more recent collections have completed, so I don't think the transforms are still running for this collection.

I also checked the `collection_note` table and couldn't see any entries relating to the collection.

**How soon do you need a fix?**

Not urgent, as the records contain compiled releases, I can use a untransformed collection for analysis.

**Comment by duncandewhurst** [comment]
Edit: Actually, this is blocking publisher feedback as I need to load the data into Pelican, which requires a compiled release collection.

**Comment by duncandewhurst** [comment]
cc @mrshll1001 - this issue affects the portugal data

**Comment by jpmckinney** [comment]
My first guess was that there was just a backlog of work in the queue:

```sql
SELECT * FROM collection WHERE transform_type IS NOT NULL AND store_end_at IS NULL ORDER BY id;
```

Indeed, there are a few stale transforms and some newer ones.

Looking at `/var/log/kingfisher.log` I could see that the desired collections were being started (transform-collections runs multiple collections in different threads), but that the command wasn't finishing with the "Finishing command" log message (it was instead stopping itself on its self-timer). For this to occur without updates to the database, it can only be:

* A bug
* Very inefficient code

As it turns out, it is very inefficient code, fixed in df349cd8da58273acc0d0ff449ee580bf5e8022d.

There was a loop where, for each OCID, it would check if it was in a list. The list started off empty, but it eventually grew to over a million. This adds up to half a trillion comparisons. Using a `set` is wayyy faster, as it is optimized for the "member in set" operation. Also the code was using `list.append`. A million of these is slow.  List comprehensions are fast.

**Comment by duncandewhurst** [comment]
Thanks, @jpmckinney. Are those changes deployed on the server so I can manually run the transforms now?

**Comment by jpmckinney** [comment]
Yes, they are currently being run automatically. It looks like 1535 is taking precedence over 1532. It also looks like after working for a while, the transform script might be timing out (could be due to holding a database connection open too long).

**Comment by jpmckinney** [comment]
Looks like both completed with 1153040 compiled releases.
