### ISSUE TITLE
'store end at' null for nigeria budeshi releases

### ISSUE THREAD

**Issue by odscrachel** [open-contracting/kingfisher-process#338]
**What were you trying to do?**

After running the [nigeria_budeshi_releases](https://kingfisher-collect.readthedocs.io/en/latest/spiders.html#kingfisher_scrapy.spiders.nigeria_budeshi_releases.NigeriaBudeshiReleases) spider (and the record spider), there were no errors in the logs but the `store_end_at` did not complete for releases, resulting in no cashed releases. Before I realized, however, I created a summarize view: view_data_collection_2146_2147_2148 which has numerous releases, similar in number to those found in the records. Any idea why the store_end_at would not complete?

Collection IDs
releases = 2146
records = 2148

**Did you attempt a fix?**

n/a

**How soon do you need a fix?**

Not urgent

**Comment by yolile** [comment]
Hi Rachel, I think this is an error in Kingfisher Collect rather than in Kingfisher process, as I see in the [logs](https://collect.kingfisher.open-contracting.org/logs/kingfisher/nigeria_budeshi_releases/1690546cbf0011ebb6530c9d92c523cb.log) that something failed when Collect tried to communicate with Process. Closing this and opening a new issue in Collect
