### ISSUE TITLE
Should we refactor collection deletion to use cascades? 

### ISSUE THREAD

**Issue by robredpath** [open-contracting/kingfisher-process#96]
Carrying on from #22 

Cascades feel like a more elegant solution to collection deletion than per-table deletions. They'd make it easier to expand the database without updating the deletion command, and fewer SQL statements generally means less room for error. 

However, we're currently concerned that cascading deletion could easily be too effective - and delete some data that we needed. Initially we've chosen the path of safety. In the future, we should consider whether the balance has changed and we want to refactor.

**Comment by odscjames** [comment]
Previous discussion in https://github.com/open-contracting/kingfisher/issues/106

I'm personally not in favour;

a) Having DELETE CASCADE opens up the door to mistakes - the safety issue mentioned. Normally this is less important - normally in an app direct database access is locked down. But given we do have people making direct connections to the database and running commands directly I think this is good

b) Because the FK's on data and package_data are reversed, we can't fully use cascade anyway. We will always need some extra process - and those 2 tables are the big ones we really want to clear out!

c) I suspect we might find that deleting really big collections will start to take a really big amount of time, and in the interests of database efficiency for other processes running at the same time we may want to have some measure of control over that. Doing it this way gives us options to delete a bit of the collection at a time in the future if needed. 

> more future-proof, so that if we add more tables that foreign-key onto these tables, we won't have to remember to update this command's code?

I would use automatic tests to help cover this.

Not to say this is final - we might look at this again later. But at this point in the sprint, I think moving the solution in working steps is good. I'm about to comment on the P.R. with some minor things, but it's basically a good start.

**Comment by robredpath** [comment]
Thanks, @odscjames . We probably want to move to a model longer-term where standard use is read-only, and people make copies of the data into their own sandbox if they're making any writes to the database. Then, the only DELETEs that are possible are the ones that the app makes.

**Comment by jpmckinney** [comment]
I'm not worried about reason (a), because as @robredpath mentioned, users shouldn't be changing the data directly, using commands instead. If they want to make direct edits/deletions (not something I'm aware anyone is doing or wants to do), then they can make a copy.

Reason (b) just means cascades aren't a comprehensive solution, which is fine – we can still use them for the part for which they're useful.

I did a bit of reading ([example](https://dba.stackexchange.com/questions/37034/very-slow-delete-in-postgresql-workaround)) on reason (c) and it seems like adding indices on foreign keys solves the problem for the number of records we're expecting to delete at once (i.e. takes only minutes). We aren't building a high-concurrency analytical system, so if the database is unavailable for other queries for a few minutes, or even an hour, it's not an issue.

**Comment by jpmckinney** [comment]
As mentioned in #271, all FKs now use delete cascade. For the reverse relationships (that can't use it), see #340
